// <auto-generated />
using System;
using Ecomindo_D1.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ecomindo_D1.Migrations
{
    [DbContext(typeof(OnBoardingSkdDbContext))]
    [Migration("20220223045952_addRestaurant")]
    partial class addRestaurant
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ecomindo_D1.Model.Menu", b =>
                {
                    b.Property<Guid>("idMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RestaurantidRestaurant")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("hargaMenu")
                        .HasColumnType("int");

                    b.Property<string>("namaMenu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idMenu");

                    b.HasIndex("RestaurantidRestaurant");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Ecomindo_D1.Model.Restaurant", b =>
                {
                    b.Property<Guid>("idRestaurant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("namaRestaurant")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idRestaurant");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("Ecomindo_D1.Model.Menu", b =>
                {
                    b.HasOne("Ecomindo_D1.Model.Restaurant", null)
                        .WithMany("Menus")
                        .HasForeignKey("RestaurantidRestaurant");
                });

            modelBuilder.Entity("Ecomindo_D1.Model.Restaurant", b =>
                {
                    b.Navigation("Menus");
                });
#pragma warning restore 612, 618
        }
    }
}
