apiVersion: batch/v1
kind: Job
metadata:
	name: init
spec:
	template:
		spec:
			containers:
			- name: init
			  image: acronboarding.azurecr.io/dotnet-raihan
			restartPolicy: Never
	backoffLimit: 4