apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      app: dotnet-raihan
  name: dotnet-raihan
spec:
  replicas: 1
  selector:
    matchLabels:
        app: dotnet-raihan
  strategy:
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
          app: dotnet-raihan
      name: dotnet-raihan
    spec:
      containers:
        - name: dotnet-raihan
          image: muhammadraihan39/onboarding:442
          imagePullPolicy: Always
          env:
            - name: CONTENT_API_URL
              value: http://api:80
          ports:
          - containerPort: 80
          resources:
            requests:
                cpu: 100m
                memory: 128Mi
            limits:
                cpu: 125m
                memory: 256Mi
      restartPolicy: Always
      serviceAccountName: ""
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnet-raihan
  name: dotnet-raihan
spec:
  ports:
  - port: 80
  type: LoadBalancer
  selector:
    app: dotnet-raihan
status:
  loadBalancer: {}
